// gh-pr-summarize Action
const { exec } = require('@actions/exec');
const { getOctokit } = require('@octokit/rest');
const core = require('@actions/core');
const fs = require('fs');
const path = require('path');
const https = require('https');

async function run() {
  try {
    const githubToken = core.getInput('github-token') || process.env.GITHUB_TOKEN;
    const openrouterApiKey = core.getInput('openrouter-api-key') || process.env.OPENROUTER_API_KEY || '';
    const model = core.getInput('model') || 'google/gemini-2.5-flash';
    const outputFormat = core.getInput('output-format') || 'markdown';
    const autoComment = (core.getInput('auto-comment') || 'true').toLowerCase() === 'true';

    const octokit = getOctokit(githubToken);

    // Get PR info
    const repoFull = process.env.GITHUB_REPOSITORY || '';
    const [owner, repo] = repoFull.split('/');
    const prMatch = process.env.GITHUB_REF?.match(/pull\/(\d+)/);
    const prNumber = prMatch ? prMatch[1] : (process.env.PR_NUMBER || '');

    if (!prNumber) {
      core.setFailed('No PR number found. This action must run on pull_request events.');
      return;
    }

    core.info(`Summarizing PR #${prNumber} in ${owner}/${repo}`);

    // Get PR details and diff
    const prResponse = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: parseInt(prNumber),
      headers: { 'Accept': 'application/vnd.github.v3.diff' },
    });

    const diff = prResponse.data;

    core.info(`Diff retrieved, length: ${diff.length} chars`);

    // Summarize with AI
    let summary = '';
    if (openrouterApiKey) {
      summary = await summarizeWithAI(diff, model, openrouterApiKey);
    } else {
      // Fallback to heuristic summary
      summary = heuristicSummary(diff);
    }

    // Output
    if (outputFormat === 'json') {
      const jsonOutput = JSON.stringify({
        pr_number: parseInt(prNumber),
        repository: `${owner}/${repo}`,
        summary,
        model: openrouterApiKey ? model : 'heuristic',
        diff_length: diff.length,
      });
      core.setOutput('summary', jsonOutput);
      fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE || '.', 'pr-summary.json'), jsonOutput);
    } else {
      core.setOutput('summary', summary);
      fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE || '.', 'pr-summary.md'), summary);
    }

    // Post comment on PR
    if (autoComment && summary) {
      try {
        await octokit.rest.issues.createComment({
          owner,
          repo,
          issue_number: parseInt(prNumber),
          body: `## Summary\n${summary}\n\n---\n*Generated by gh-pr-summarize*`,
        });
        core.info('Comment posted to PR');
      } catch (e) {
        core.warning(`Could not post comment: ${e.message}`);
      }
    }

    core.info('Summary complete!');

  } catch (error) {
    core.setFailed(error.message);
  }
}

async function summarizeWithAI(diff, model, apiKey) {
  const truncatedDiff = diff.substring(0, 8000);
  const prompt = `Analyze this Git diff and create a concise PR summary. Structure as:
## Summary
2-3 sentences describing what this PR does.
## Key Changes
- List key changes (2-3 bullet points)
## Impact
- Test coverage impact and deployment risk (low/medium/high)
## Risk Assessment
- Deployment risk with 1-sentence justification
Format as Markdown. Keep professional.

\`\`\`diff
${truncatedDiff}
\`\`\``;

  return new Promise((resolve) => {
    const body = JSON.stringify({
      model: model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 2000,
    });

    const req = https.request('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body),
        'HTTP-Referer': 'https://github.com/13DJTEQ/gh-pr-summarize',
        'X-Title': 'GH PR Summarize Action',
      },
    }, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(data);
          if (json.choices && json.choices[0]) {
            resolve(json.choices[0].message.content);
          } else if (json.error) {
            resolve(`Error: ${json.error.message}\n\n${heuristicSummary('')}`);
          } else {
            resolve(heuristicSummary(''));
          }
        } catch (e) {
          resolve(`AI summary unavailable.\n\n${heuristicSummary('')}`);
        }
      });
    });

    req.on('error', () => resolve(heuristicSummary('')));
    req.write(body);
    req.end();
  });
}

function heuristicSummary(diff) {
  const lines = diff.split('\n');
  const added = lines.filter(l => l.startsWith('+') && !l.startsWith('+++')).length;
  const removed = lines.filter(l => l.startsWith('-') && !l.startsWith('---')).length;
  const files = [...new Set(lines.filter(l => l.startsWith('diff --git')).map(l => {
    const match = l.match(/diff --git a\/(.+?) b\//);
    return match ? match[1] : '';
  }).filter(Boolean))];

  const risk = added + removed > 100 ? 'medium' : (added + removed > 500 ? 'high' : 'low');

  return `## Summary\nAuto-generated summary. Configure OPENROUTER_API_KEY for AI-powered analysis.\n\n## Key Changes\n- ${added} lines added, ${removed} lines removed\n- Files modified: ${files.join(', ') || 'N/A'}\n\n## Impact\n- Deployment risk: **${risk}**\n\n## Risk Assessment\n- Risk assessed as ${risk} based on lines changed.\n`;
}

run();